Repository E3SM-Project/Omega, pull requests merged in 2023-06, with the labels that each got.

#13 Added design document for OMEGA metadata management
  components/omega/doc/design/Metadata.md
Labels: Omega, Design

#20 Add metadata design doc to table of contents
  components/omega/doc/design/Metadata.md
  components/omega/doc/index.md
Labels: documentation

#22 Fix `.clang-format`
  .pre-commit-config.yaml
Labels: bug, linting and CI

#25 simplify clang format
  .clang-format
Labels: bug
