Repository E3SM-Project/Omega, pull requests merged in 2024-09, with the labels that each got.

#123 Add Omega standalone driver
  components/omega/OmegaBuild.cmake
  components/omega/configs/Default.yml
  components/omega/configs/UnitTests.yml
  components/omega/doc/devGuide/Driver.md
  components/omega/doc/devGuide/QuickStart.md
  components/omega/doc/index.md
  components/omega/doc/userGuide/Driver.md
  components/omega/doc/userGuide/TendencyTerms.md
  components/omega/src/CMakeLists.txt
  components/omega/src/base/Decomp.cpp
  components/omega/src/drivers/standalone/OceanDriver.cpp
  components/omega/src/infra/Config.cpp
  components/omega/src/infra/TimeMgr.cpp
  components/omega/src/infra/TimeMgr.h
  components/omega/src/ocn/AuxiliaryState.cpp
  components/omega/src/ocn/AuxiliaryState.h
  components/omega/src/ocn/HorzMesh.cpp
  components/omega/src/ocn/HorzMesh.h
  components/omega/src/ocn/OceanDriver.h
  components/omega/src/ocn/OceanFinal.cpp
  components/omega/src/ocn/OceanInit.cpp
  components/omega/src/ocn/OceanRun.cpp
  components/omega/src/ocn/OceanState.cpp
  components/omega/src/ocn/TendencyTerms.cpp
  components/omega/src/ocn/TendencyTerms.h
  components/omega/src/ocn/auxiliaryVars/LayerThicknessAuxVars.cpp
  components/omega/src/ocn/auxiliaryVars/LayerThicknessAuxVars.h
  components/omega/src/timeStepping/TimeStepper.cpp
  components/omega/src/timeStepping/TimeStepper.h
  components/omega/test/CMakeLists.txt
  components/omega/test/base/DecompTest.cpp
  components/omega/test/base/HaloTest.cpp
  components/omega/test/base/IOTest.cpp
  components/omega/test/drivers/StandaloneDriverTest.cpp
  components/omega/test/infra/ConfigTest.cpp
  components/omega/test/infra/DimensionTest.cpp
  components/omega/test/infra/FieldTest.cpp
  components/omega/test/infra/TimeMgrTest.cpp
  components/omega/test/ocn/AuxiliaryStateTest.cpp
  components/omega/test/ocn/AuxiliaryVarsTest.cpp
  components/omega/test/ocn/HorzMeshTest.cpp
  components/omega/test/ocn/HorzOperatorsTest.cpp
  components/omega/test/ocn/StateTest.cpp
  components/omega/test/ocn/TendenciesTest.cpp
  components/omega/test/ocn/TendencyTermsTest.cpp
  components/omega/test/timeStepping/TimeStepperTest.cpp
Labels: Omega

#127 Indent YAMLs by 2 spaces, not 3.
  components/omega/configs/Default.yml
  components/omega/configs/UnitTests.yml
Labels: clean up

#125 Fix warning when `RunDuration` and `StopTime` are inconsistent
  components/omega/src/ocn/OceanInit.cpp
Labels: bug

#130 Fix tendency terms test
  components/omega/test/ocn/TendencyTermsTest.cpp
Labels: Omega, YAML

#136 fixed bugs in Omega logging
  components/omega/OmegaBuild.cmake
  components/omega/doc/devGuide/CMakeBuild.md
  components/omega/src/infra/LogFormatters.h
  components/omega/src/infra/Logging.cpp
  components/omega/src/infra/Logging.h
  components/omega/test/infra/LoggingTest.cpp
  components/omega/test/infra/TracersTest.cpp.2
Labels: Omega, Logging

#138 Add a critical error if TimeStepper is invalid
  components/omega/src/timeStepping/TimeStepper.cpp
  components/omega/src/timeStepping/TimeStepper.h
Labels: bug

#139 Update pre-commit dependencies
  .pre-commit-config.yaml
Labels: linting and CI
